services:
  # Postgres Service
  postgres:
    image: docker-repo.omaxplatform.com/postgres:alpine
    container_name: postgres.${APP_NAME}
    restart: unless-stopped
    ports:
      - ${DB_PORT:-5433}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      TZ: ${APP_TZ}
    volumes:
      - telegram:/var/lib/postgresql/data
    networks:
      - telegram
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # CockroachDB Service
  crdb:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb.${APP_NAME}
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
    networks:
      - telegram
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/_status/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  telegram:
    external: true
  cockroach:
    external: true

networks:
  telegram:
    driver: bridge
